name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up Datadog Tracing (optional)
        run: |
          # Ensure DD_API_KEY and DD_ENV variables are set
          echo "DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
          echo "DD_ENV=ci" >> $GITHUB_ENV
          echo "DD_SERVICE=your-service-name" >> $GITHUB_ENV

          # Install and configure Datadog tracing libraries (if you have one set up for Node.js)
          npm install dd-trace

          # Initialize Datadog Tracing in your app (if necessary)
          echo "require('dd-trace').init()" > ./tracing-init.js

      - name: Run tests with traces
        run: |
          # Run your application with tracing enabled
          node -r ./tracing-init.js your-test-script.js
          
          npm test
