name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Updated to Node.js v16

      - name: Install dependencies
        run: npm install

      - name: Set up Datadog Tracing
        run: |
          # Set Datadog environment variables (if you haven't already set them in the repository secrets)
          echo "DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
          echo "DD_ENV=ci" >> $GITHUB_ENV
          echo "DD_SERVICE=your-service-name" >> $GITHUB_ENV

          # Install Datadog tracing library for Node.js
          npm install dd-trace

          # Initialize Datadog Tracing (if applicable, adjust according to your setup)
          echo "require('dd-trace').init();" > ./tracing-init.js

      - name: Run tests with traces
        run: |
          # Ensure tracing is initialized and then run tests
          node -r ./tracing-init.js ./node_modules/.bin/mocha || npm test
