name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Datadog CLI
        run: npm install -g @datadog/datadog-ci
      - name: Install dependencies
        run: npm install

      - name: Install Datadog Agent
        run: |
          DD_API_KEY=4b3dc7d3beead01638572924b8e377d1 DD_SITE="us5.datadoghq.com" bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"

      - name: Run Pipeline with Datadog Trace
        continue-on-error: true
        env:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
          DATADOG_SITE: "datadoghq.com"
        run: |
          datadog-ci tag --level pipeline --name branch --value $(git rev-parse --abbrev-ref HEAD)
          datadog-ci tag --level job --name job_id --value $GITHUB_RUN_ID
          datadog-ci trace -- npm test

      - name: Forward Logs to Datadog
        env:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
        run: |
          datadog-ci tag --level job --name job_id --value $GITHUB_RUN_ID
          datadog-ci junit upload --service my-service test-results.xml
